"""Type stub for the saxonche native extension.

architecture.md Part I §1.8(4): saxonche is imported only in engine.py. This stub
types that single boundary so `mypy --strict` checks engine.py against real
signatures instead of against `Any`.

It deliberately covers ONLY the API surface engine.py uses. Adding a symbol here
without using it invites drift between the stub and the extension; if engine.py
needs a new call, add it here in the same commit.

Verified against SaxonC-HE 13.0 (saxonche==13.0.0).
"""

from types import TracebackType

class PySaxonApiError(Exception): ...

class PyXdmItem:
    def get_string_value(self) -> str: ...
    def get_node_value(self) -> PyXdmNode: ...

# PyXdmNode extends PyXdmItem in the extension, which is what makes the result
# of parse_xml() directly usable as an XPath context item.
class PyXdmNode(PyXdmItem):
    @property
    def name(self) -> str: ...

class PyXdmValue:
    @property
    def size(self) -> int: ...
    def item_at(self, index: int) -> PyXdmItem: ...

class PyXPathProcessor:
    def declare_namespace(self, prefix: str, uri: str) -> None: ...
    def set_context(self, *, xdm_item: PyXdmItem) -> None: ...
    def evaluate(self, xpath_str: str) -> PyXdmValue | None: ...
    def evaluate_single(self, xpath_str: str) -> PyXdmItem | None: ...
    def effective_boolean_value(self, xpath_str: str) -> bool: ...

class PySaxonProcessor:
    def __init__(self, *, license: bool = False) -> None: ...
    def __enter__(self) -> PySaxonProcessor: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    @property
    def version(self) -> str: ...
    def parse_xml(self, *, xml_text: str) -> PyXdmNode: ...
    def new_xpath_processor(self) -> PyXPathProcessor: ...
