/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Validate the golden invoice. Not {"ok": true}.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Specs */
        get: operations["specs_specs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EngineFailureBody */
        EngineFailureBody: {
            /** Correlation Id */
            correlation_id: string;
            /**
             * Error
             * @default engine_failure
             * @constant
             */
            error: "engine_failure";
        };
        /**
         * Finding
         * @description One rule outcome. Part III §5.
         *
         *     `message` is templated from `value_shape` by redaction.py and never
         *     interpolates the offending value. `value_shape` is the only representation
         *     of that value which crosses this boundary.
         */
        Finding: {
            /** Business Term */
            business_term?: string | null;
            /** Failure Class */
            failure_class?: ("missing_mandatory" | "invalid_code" | "format_mismatch" | "arithmetic_mismatch" | "identifier_invalid" | "cardinality" | "cross_field_dependency" | "encoding" | "date_logic" | "rounding") | null;
            /** Message */
            message?: string | null;
            /** Native Rule Code */
            native_rule_code?: string | null;
            /** Rule Id */
            rule_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "fatal" | "error" | "warning";
            value_shape?: components["schemas"]["ValueShape"] | null;
            /** Xpath */
            xpath?: string | null;
        };
        /**
         * HealthResponse
         * @description Part III §5 and Part V §2: /health VALIDATES A GOLDEN INVOICE.
         *
         *     Not {"ok": true}. If Saxon dies or a spec file goes missing, health goes red.
         */
        HealthResponse: {
            /**
             * Checked Spec Id
             * @enum {string}
             */
            checked_spec_id: "pint-ae" | "en16931" | "peppol-bis-3.0" | "factur-x" | "xrechnung" | "ksef-fa3";
            /** Detail */
            detail?: string | null;
            /** Golden Invoice Outcome */
            golden_invoice_outcome: ("pass" | "fail" | "warn") | null;
            /** Ruleset Hash */
            ruleset_hash: string | null;
            /** Saxon Version */
            saxon_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * InvalidRequestBody
         * @description Redacted schema-violation body.
         *
         *     Part III §5 defines four error conditions but not this one, and FastAPI will
         *     return *something* for a malformed request regardless. Declaring the shape
         *     here means it is (a) generated into the contract so the web app can type it
         *     and (b) known not to echo the document — the framework default puts the
         *     offending input in the body, and here that input is an invoice.
         */
        InvalidRequestBody: {
            /**
             * Error
             * @default invalid_request
             * @constant
             */
            error: "invalid_request";
            /** Fields */
            fields: string[];
        };
        /** ParseErrorBody */
        ParseErrorBody: {
            /** Column */
            column: number;
            /**
             * Error
             * @default parse_error
             * @constant
             */
            error: "parse_error";
            /** Line */
            line: number;
        };
        /** SpecDescriptor */
        SpecDescriptor: {
            /** Jurisdiction */
            jurisdiction: string;
            /**
             * Resolved
             * @description False while `version` is the RESOLVE_IN_WEEK_1 sentinel. An unresolved spec is refused by /validate unless CDL_ALLOW_PROVISIONAL_RULESET=1. architecture.md 'How an agent must use this file' (2).
             */
            resolved: boolean;
            /**
             * Ruleset Hash
             * @description null only when `unavailable` is set. A quarantined profile has no compiled ruleset, so it has no hash — and reporting a plausible one would let a caller record a finding against a hash that never produced it.
             */
            ruleset_hash: string | null;
            /**
             * Spec Id
             * @enum {string}
             */
            spec_id: "pint-ae" | "en16931" | "peppol-bis-3.0" | "factur-x" | "xrechnung" | "ksef-fa3";
            /** Syntaxes */
            syntaxes: ("UBL-2.1" | "CII-D16B")[];
            /**
             * Unavailable
             * @description When non-null, the profile is quarantined and /validate refuses it unconditionally — the flag does not unlock a quarantine. The string states who withdrew it and on what evidence. The profile is still listed rather than hidden: a caller that has been sending this profile needs to find out why it stopped, not watch it vanish.
             */
            unavailable?: string | null;
            /** Version */
            version: string;
        };
        /** SpecsResponse */
        SpecsResponse: {
            /** Specs */
            specs: components["schemas"]["SpecDescriptor"][];
        };
        /** UnknownSpecBody */
        UnknownSpecBody: {
            /** Available */
            available: string[];
            /**
             * Error
             * @default unknown_spec
             * @constant
             */
            error: "unknown_spec";
        };
        /** ValidateOptions */
        ValidateOptions: {
            /**
             * Include Warnings
             * @default true
             */
            include_warnings: boolean;
            /**
             * Stop On First Error
             * @description Set by the caller on a 504 retry. Part IV §4 job 4.
             * @default false
             */
            stop_on_first_error: boolean;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /**
             * Direction
             * @default ar
             * @enum {string}
             */
            direction: "ar" | "ap";
            /**
             * Document
             * @description Base64-encoded source document.
             */
            document: string;
            options?: components["schemas"]["ValidateOptions"];
            /**
             * Profile
             * @enum {string}
             */
            profile: "pint-ae" | "en16931" | "peppol-bis-3.0" | "factur-x" | "xrechnung" | "ksef-fa3";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Spec Version */
            spec_version: string;
            /**
             * Syntax
             * @enum {string}
             */
            syntax: "UBL-2.1" | "CII-D16B";
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "fail" | "warn";
            /**
             * Ruleset Hash
             * @description sha256 of the compiled ruleset, 'sha256:...'. MUST be persisted on every finding and validation event — two invocations of the same rule under different ruleset hashes are different facts.
             */
            ruleset_hash: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Spec Id
             * @enum {string}
             */
            spec_id: "pint-ae" | "en16931" | "peppol-bis-3.0" | "factur-x" | "xrechnung" | "ksef-fa3";
            /** Spec Version */
            spec_version: string;
            /** Timing Ms */
            timing_ms: number;
        };
        /**
         * ValueShape
         * @description The only representation of a failing value that crosses the boundary.
         *
         *     Field names are the wire contract (architecture.md Part III §5) and match
         *     `packages/db/schema/_shared.ts` `ValueShape` on the TypeScript side.
         */
        ValueShape: {
            /**
             * Charset
             * @description Coarse character class of the whole value.
             */
            charset?: ("numeric" | "alpha" | "alnum" | "mixed" | "empty") | null;
            /**
             * Expected
             * @description Pattern the rule required. Rule metadata, not client data.
             */
            expected?: string | null;
            /**
             * Len
             * @description Character count, or null when the value is absent.
             */
            len?: number | null;
            /**
             * Regex Class
             * @description Character-class signature. Never contains value characters.
             */
            regex_class?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    specs_specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecsResponse"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Unknown or unusable profile. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnknownSpecBody"];
                };
            };
            /** @description Malformed document, or a request that failed schema validation. Never echoes document content. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseErrorBody"] | components["schemas"]["InvalidRequestBody"];
                };
            };
            /** @description Saxon or ruleset failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineFailureBody"];
                };
            };
        };
    };
}
